OUTPUT_TYPE := cma
LLVM_LIB := /home/jianzhou/Tools/llvm-2.6/lib/
LLVM_OCAML_LIB := $(LLVM_LIB)/ocaml/

all: symexe

symexe: symexe.ml symexe.mli
	./fixocaml.py
	mv _tmp_symexe.mli symexe.mli
	ocamlbuild -j 2 -cflags -g,-I,$(LLVM_OCAML_LIB) -lflags -g,-I,$(LLVM_OCAML_LIB),-cclib,-L$(LLVM_LIB) symexe.$(OUTPUT_TYPE)

.PHONY: wc
wc:
	wc symexe.ml

.PHONY: clean
clean:
	ocamlbuild -clean

