OTT = ott
COQC = coqc
COQDEP = coqdep
COQDOC = coqdoc
LNGEN = lngen  # optional

RELEASE = $(HOME)/src/vol
METALIB = $(RELEASE)/theory/metatheory_8.3
LLVM_LIB = $(HOME)/Tools/llvm-3.0/lib/
LLVM_OCAML_LIB = $(LLVM_LIB)/ocaml/
EXTRACTION_LIB = $(RELEASE)/vol/src3.0/Extraction/_build/
