target=$1

mkdir -p $target/Vellvm/
mkdir -p $target/Vellvm/ott
mkdir -p $target/Vellvm/monads
mkdir -p $target/Vellvm/compcert
mkdir -p $target/Vellvm/Dominators
mkdir -p $target/Vellvm/GraphBasics
mkdir -p $target/Transforms/
mkdir -p $target/Extraction/
mkdir -p $target/Vminus/
cp Vminus/*.v $target/Vminus/
cp Vminus/*.ott $target/Vminus/
#cp Vminus/Makefile $target/Vminus/
cp Vellvm/*.ott $target/Vellvm/
cp Vellvm/*.v $target/Vellvm/
cp Vellvm/compcert/*.v $target/Vellvm/compcert
cp Vellvm/ott/*.v $target/Vellvm/ott
cp Vellvm/Dominators/*.v $target/Vellvm/Dominators
cp Vellvm/Dominators/README $target/Vellvm/Dominators
cp Vellvm/Dominators/main.ml $target/Vellvm/Dominators
cp Vellvm/GraphBasics/*.v $target/Vellvm/GraphBasics
cp Vellvm/monads/*.v $target/Vellvm/monads
cp Transforms/*.v $target/Transforms/
cp Transforms/*.ml $target/Transforms/
cp Transforms/_tags $target/Transforms/
cp Transforms/README $target/Transforms/
rm -rf $target/Transforms/vmem2reg_opt_correct.v
rm -rf $target/Transforms/vmem2reg_opt_compose_props.v
cp Extraction/extraction_core.v $target/Extraction/
cp Extraction/extraction_trans.v $target/Extraction/
cp Extraction/*.ml $target/Extraction/
#cp Extraction/Makefile $target/Extraction/
#cp Extraction/Makefile.ocaml $target/Extraction/
#cp Extraction/Makefile.coq $target/Extraction/
#cp Extraction/Make $target/Extraction/
cp Extraction/fixextract.py $target/Extraction/
cp .dir-locals.el.sample $target/
cp .dir-locals.el $target/
#cp Make $target/
#cp Makefile $target/
#cp Makefile.config $target/
#cp Makefile.config.sample $target/
#cp Makefile.coq.common $target/
#cp myocamlbuild.ml $target/
