#!/bin/sh

git svn clone https://webdav.seas.upenn.edu/svn/sol/vol --ignore-paths=\
"^(doc\
|Vminus\
|softbound_test\
|optimizations_test\
|extralibs\
|undef_tests\
|examples\
|misc\
|scripts\
|src/Parser/tvcases\
|src3.0/Parser/tvcases\
|src/Interpreter/testcases\
|src3.0/Interpreter/testcases\
|src/.metadata\
|src3.0/.metadata\
|src/Transforms/log\
|src3.0/Transforms/log\
|src/Transforms/testcases\
|src3.0/Transforms/testcases\
|src3.0/Vellvm/Dominators/worstcases\
|src3.0/Vellvm/Dominators/experiments\
|src3.0/Vellvm/Dominators/log\
|src3.0/llvm-3.0.src\
|src/Interpreter/report\
|src3.0/Interpreter/report\
|src/Vellvm/GraphBasics\
|src3.0/Vellvm/GraphBasics\
|src/Vminus\
|src3.0/Vminus\
|src/Extraction\
|src3.0/Extraction\
|src/Vellvm/compcert\
|src3.0/Vellvm/compcert\
|src3.0/Vellvm/Dominators/cpdt_tactics.v\
|src3.0/Vellvm/events.v\
)"
