OTT = ott
COQC = coqc
COQDEP = coqdep
COQDOC = coqdoc
LNGEN = lngen  # optional

RELEASE = $(ROOT)/vellvm3.0-interp
LIB = $(RELEASE)/lib
METALIB = $(LIB)/metatheory_8.4
EQUATIONS = $(LIB)/Coq-Equations-8.4-1
