OTT = ott
COQC = coqc
COQDEP = coqdep
COQDOC = coqdoc
LNGEN = lngen  # optional

RELEASE = /Users/stevez/research/sol
METALIB = $(RELEASE)/theory/metatheory_8.3
LLVM_LIB = /Users/stevez/software/llvmz/lib
LLVM_OCAML_LIB = $(LLVM_LIB)/ocaml
EXTRACTION_LIB = $(RELEASE)/vol/src/Extraction/_build
