
include ../../Makefile.config

all: _build/ssa_def.cma _build/ssa_lib.cma _build/eq_tv.cma _build/sub_tv.cma

_build/%.cma: %.ml %.mli $(LLVM_OCAML_LIB)/llvm.cma
	./fixextract.py
	ocamlbuild -j 2 -cflags -g,-I,$(LLVM_OCAML_LIB) -lflags -g,-I,$(LLVM_OCAML_LIB),-cclib,-L$(LLVM_LIB) $*.cma

.PHONY: clean
clean:
	ocamlbuild -clean

