OUTPUT_TYPE := native
LLVM_LIB := /home/jianzhou/Tools/llvm-2.6/lib/
LLVM_OCAML_LIB := $(LLVM_LIB)/ocaml/

all: ssa_main

ssa_main: ssa_main.ml $(LLVM_OCAML_LIB)/llvm.cma
	./fixextract.py
	ocamlbuild -j 2 -cflags -g,-I,$(LLVM_OCAML_LIB) -lflags -g,-I,$(LLVM_OCAML_LIB),-cclib,-lffi,-cclib,-L$(LLVM_LIB) ssa_main.$(OUTPUT_TYPE)

.PHONY: wc
wc:
	wc *.ml

.PHONY: clean
clean:
	ocamlbuild -clean

